// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvvhhtvtweqwfksrbsqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dmhodHZ0d2Vxd2Zrc3Jic3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODk3MDMsImV4cCI6MjA2NTI2NTcwM30.ocRj_4aLXE-_fff2fb9QLqdIdSbl-3A_ZRm5aQqCDI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);