// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configurações para Supabase Self-hosted
export const SUPABASE_URL = "https://supabase.nutef.com";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpcyI6ICJzdXBhYmFzZSIsCiAiaWF0IjogMTcxNTA1MDgwMCwKICAiZXhwIjogMTg3MjgxNzIwMAp9.zii4FynaxJNS8fGXKYKcnqiUw0DzIuLFB0MMz4ImjEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Configuração temporária para usar bucket public para áudios
export const AUDIO_BUCKET = 'public';
export const AUDIO_FOLDER = 'audio';